---
title: "Cambiamento prima e dopo rigaurdo all'attivita' fisica"
author: "Anna Quaglieri"
date: "30/05/2020"
output: 
  html_document:
    toc: true
---


```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(readr)
library(tidyverse)
library(googledrive)
library(here)
library(ggalluvial)
library(modelsummary)
```

# Dati iniziali 

```{r read-data}
data <- read_csv(file.path(here(),"data/risposte-rename.csv"))
```

# Prima/Durante quarantena attivita' fisica

```{r}
tab <- data.frame(table(data$ex_pre_si_no, data$ex_durante_si_mp)) %>%
  dplyr::rename(`Prima` = Var1,
                `Durante` = Var2)

ggplot(as.data.frame(tab),
       aes(y = Freq, axis1 = `Prima`, axis2 = `Durante`)) +
  geom_alluvium(aes(fill=`Prima`)) +
  geom_stratum(width = 4/12) +
  geom_text(stat = "stratum", infer.label = TRUE) +
  scale_x_discrete(limits = c("Prima", "Durante")) +
  scale_fill_brewer(type = "qual", palette = "Set1")+
  theme_minimal()+
  labs(y = "Numero persone", fill = "Risposta prima della quarantena") +
  ggtitle("Effetto della quarantena su attivita' fisica")
```


```{r}
knitr::kable(tab)
```


# Cambiamento nella frequenza dell'attivita' fisica

```{r all-plot-frequenza}
tab <- data.frame(table(data$ex_pre_frequenza, data$ex_durante_frequenza)) %>%
  dplyr::rename(Prima = Var1,
                Durante = Var2) %>%
  mutate(Prima = factor(Prima, levels = c("Tutti i giorni", "Almeno 3 volte a settimana",
                                          "1 o 2 volte a settimana","Meno di una volta a settimana"), 
                        labels = c("Ogni giorno","Almeno 3", "1 o 2", "Meno di una")),
         Durante = factor(Durante, levels = c("Tutti i giorni", "Almeno 3 volte a settimana",
                                          "1 o 2 volte a settimana","Meno di una volta a settimana"), 
                        labels = c("Ogni giorno","Almeno 3", "1 o 2", "Meno di una")))

ggplot(as.data.frame(tab),
       aes(y = Freq, axis1 = `Prima`, axis2 = `Durante`)) +
  geom_alluvium(aes(fill=`Prima`)) +
  geom_stratum(width = 2/12,) +
  geom_text(stat = "stratum", infer.label = TRUE) +
  scale_x_discrete(limits = c("Prima", "Durante"), expand = c(0.03, .03)) +
  scale_fill_brewer(type = "qual", palette = "Set1")+
  theme_minimal()+
  labs(y = "Numero persone", fill = "Risposta prima della quarantena") +
  ggtitle("Cambiamento nella frequenza dell'attivita' fisica praticata")+
  theme(legend.position = "bottom")
```


```{r barplot-frequenza}
tab_long <- data %>%
  gather(key = Periodo, value = Frequenza, ex_pre_frequenza,ex_durante_frequenza) 

ggplot(tab_long, aes(x = Frequenza, fill = Periodo)) +
  geom_bar(position = "dodge", colour="white") +
  theme_bw() + coord_flip()
```


```{r}
knitr::kable(tab)
```



```{r}

```


