---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

# Domande principali della ricerca

- Se la quarantena ha avuto un aspetto positivo/negativo/neutro sulla pratica di attivita' fisica e sulla forma fisica
- Che impatto ha avuto la quarantena sull'umore delle persone e se questo puo' essere associato alla pratica di attivita' fisica

## [Demografia del campione](2.0-demografia-del-campione.html)

Descrizione del campione che siamo riusciti a raggiungere:

  - Eta', geografia
  - Se praticavano, che tipo di sport praticavano?

## [Effetto della quarantena sull'attivita' fisica](3.0-effetto-su-attivita-fisica.html)

1. Qual e' stato l'effetto della quarantena sull'attitudine a praticare attivita' fisica?

  - Mostra come e' cambiata la disposizione a paticare attivita' fisica prima e dopo la quarante. Ad esempio, quanti di quelli che praticavano prima praticano anche durante o hanno smesso e viceversa. 

2. Quali sono le motivazioni principali che hanno determinato un cambiamento nell'attitudine a praticare attivita' fisica?
  - Analizza le motivazioni di quelli che da non praticare prima della quarantena hanno iniziato a praticare e viceversa.
  

3. Qual e' stato l'effetto della quarantena sulla frequenza della pratica di attivita' fisica?

  - Mostra come e' cambiata la frequenza nella pratica dell'attivita' fisica prima e dopo la quarante. Ad esempio, quanti di quelli che praticavano prima solo una volta  settimana durante la quarantena hanno aumentato o diminuito etc.. 


4. Per quelli che praticavano anche prima della quarantena, come si sono adattati alla situazione?
  - Usano ancora un personal trainer?
  - Come e' cambiato il metodo di allenamento (da fuori al chiuso o online?)
  

5. Quelli che hanno praticato attivita' durante la quarantena, percepiscono un miglioramento nella loro forma fisica?

6. Analizza complessivamente diversi fattori quantitativi che possono aver contributo al cambiamento nella pratica dell'attivita' fisica:
  - Se prima praticavano o no
  - L'eta'
  - In che tipo di casa/paese abitano 
  - lavoro che praticano
  - Provincia/regione di provenienza (plotta prima e dopo rispetto alle regioni)
  
## [Aspetto umorale](4.0-benessere-umorale.html) 

1. C'e' stata una diminuzione o aumento in generale dei diversi tipi di umore?
2. La differenza e' stata influenzata dalla pratica di attivita'?
3. Modelli per vedere l'effetto di eta, sesso, pratica sulle senzaioni
4. Distribuzione geografica delle sensazioni 

